runtime: python39
env: standard
entrypoint: gunicorn -b :$PORT courses_api.wsgi:application

handlers:
- url: /static              
  static_dir: staticfiles/     
- url: /.*
  script: auto

runtime_config:
  python_version: 3